name: sysqube_intern
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.2.2
  get: ^4.7.3
  http: ^1.6.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
